version: '3.8'
services:
  hospital-service:
    build:
      context: ./backend/Hospital
    command: "java -jar app.jar"
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    command: npm run preview
    ports:
      - "3000:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
