version: 2.1

orbs:
  docker: circleci/docker@2.1
  maven: circleci/maven@1.4.1

jobs:
  build_hospital_service:
    docker:
      - image: openjdk:22-jdk-slim
    working_directory: ~/project/backend/Hospital
    steps:
      - run:
          name: Install Maven
          command: |
            apt-get update && apt-get install -y maven
      - run:
          name: Build and test Hospital service
          command: |
            ls -al
            mvn clean install
  build_frontend:
    docker:
      - image: cimg/node:14.17
    working_directory: ~/project/frontend
    steps:
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run unit tests 
          command: |
            ls -al
            npm run test
      - run:
          name: Run e2e tests 
          command: npm run test:e2e
      - run:
          name: Build 
          command: npm run build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_hospital_service
      - build_frontend:
          requires:
            - build_hospital_service

