version: 2.1

orbs:
  docker: circleci/docker@2.1
  maven: circleci/maven@1.4.1

jobs:
  build_hospital_service:
    docker:
      - image: openjdk:22-jdk-slim
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            apt-get update && apt-get install -y maven
      - run:
          name: Build and test Hospital service
          command: |
            cd backend/Hospital
            mvn clean install
  build_frontend:
    docker:
      - image: cimg/node:22.2.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run tests and build
          command: |
            cd frontend
            npm install
            npm run test
            npm run test:e2e
            npm run build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_hospital_service
      - build_frontend:
          requires:
            - build_hospital_service

