version: 2.1

orbs:
  docker: circleci/docker@2.1

jobs:
   

  build_backend:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/repo/backend
    steps:
      - checkout
      - run:
          name: Select subdirectory
          command: cd backend
      - run:
          name: Build and test backend
          command: |
            mvn clean install

  build_frontend:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build and test frontend
          command: |
            npm run build
            npm run test

  build_and_push_docker_images:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Docker Images
          command: |
            docker build -t orgname/backend:${CIRCLE_SHA1} ./backend
            docker build -t orgname/frontend:${CIRCLE_SHA1} ./frontend
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Images
          command: |
            docker push orgname/backend:${CIRCLE_SHA1}
            docker push orgname/frontend:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_backend
      - build_frontend:
          requires:
            - build_backend
      - build_and_push_docker_images:
          requires:
            - build_frontend
