version: 2.1

orbs:
  docker: circleci/docker@2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/base:stable  # Image de base pour les opérations CI
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose  # Installer Docker Compose si nécessaire
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Build Services
          command: docker-compose build  # Construire les services sans les démarrer

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
